// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANTtZiY9NszqyS367yUCdGN21fAjNYN9E',
    appId: '1:1035442472174:web:3f86e52d4b4f4f7d03dfff',
    messagingSenderId: '1035442472174',
    projectId: 'harlem-storage2024',
    authDomain: 'harlem-storage2024.firebaseapp.com',
    databaseURL: 'https://harlem-storage2024-default-rtdb.firebaseio.com',
    storageBucket: 'harlem-storage2024.appspot.com',
    measurementId: 'G-3EHFVC5PRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBybXZnfssXy6AT7gLt2EBruAq8A17jQRA',
    appId: '1:1035442472174:android:1575557fd3d85e3703dfff',
    messagingSenderId: '1035442472174',
    projectId: 'harlem-storage2024',
    databaseURL: 'https://harlem-storage2024-default-rtdb.firebaseio.com',
    storageBucket: 'harlem-storage2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PoiUINJX7tFMf7-arDEG962V4ZG6-tQ',
    appId: '1:1035442472174:ios:7447030e5dd1812003dfff',
    messagingSenderId: '1035442472174',
    projectId: 'harlem-storage2024',
    databaseURL: 'https://harlem-storage2024-default-rtdb.firebaseio.com',
    storageBucket: 'harlem-storage2024.appspot.com',
    iosBundleId: 'com.example.smsReceiveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_PoiUINJX7tFMf7-arDEG962V4ZG6-tQ',
    appId: '1:1035442472174:ios:7447030e5dd1812003dfff',
    messagingSenderId: '1035442472174',
    projectId: 'harlem-storage2024',
    databaseURL: 'https://harlem-storage2024-default-rtdb.firebaseio.com',
    storageBucket: 'harlem-storage2024.appspot.com',
    iosBundleId: 'com.example.smsReceiveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANTtZiY9NszqyS367yUCdGN21fAjNYN9E',
    appId: '1:1035442472174:web:73cdfdef1e7e651103dfff',
    messagingSenderId: '1035442472174',
    projectId: 'harlem-storage2024',
    authDomain: 'harlem-storage2024.firebaseapp.com',
    databaseURL: 'https://harlem-storage2024-default-rtdb.firebaseio.com',
    storageBucket: 'harlem-storage2024.appspot.com',
    measurementId: 'G-VX4HKHYPMM',
  );
}
